name: Build iOS app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: iOS debug build
        run: cd iosApp && xcodebuild -scheme iosApp -configuration Debug -destination 'id=98CB1710-8715-4EFC-87BF-070976F6498F' CODE_SIGNING_ALLOWED='NO'
      - name: Find and upload iOS app artifact
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "KMP*.app" -path "*/Debug-iphonesimulator/*" -type d)
          echo "Found app at: $APP_PATH"
          if [ -n "$APP_PATH" ]; then
            cp -r "$APP_PATH" ./KMP_App.app
          else
            echo "No app found!"
            exit 1
          fi

      - name: Upload iOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-debug
          path: KMP_App.app
          retention-days: 7