name: Build iOS app

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    # Only run build in template repo
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: List available simulators
        run: xcrun simctl list devices
      - name: iOS debug build
        run: |
          cd iosApp
          xcodebuild \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=18.6,name=iPhone 16 Pro' \
            CODE_SIGNING_ALLOWED=NO build
