name: Build iOS app

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      # Build Kotlin framework first
      - name: Build Kotlin Framework
        run: ./gradlew :shared:embedAndSignAppleFrameworkForXcode

      # Let xcodebuild pick any available simulator
      - name: iOS debug build
        run: cd iosApp && xcodebuild -scheme iosApp -configuration Debug -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED='NO' -allowProvisioningUpdates