name: Build iOS app for Device Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Device-Runnable iOS IPA
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Import development certificate and provisioning profile
      - name: Import Code-Signing Certificates
        if: ${{ env.APPLE_DEV_CERTIFICATE_BASE64 != '' }}
        env:
          APPLE_DEV_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEV_CERTIFICATE_BASE64 }}
          APPLE_DEV_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEV_CERTIFICATE_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "" build.keychain
          
          # Import certificate
          echo "$APPLE_DEV_CERTIFICATE_BASE64" | base64 -d > certificate.p12
          security import certificate.p12 -k build.keychain -P "$APPLE_DEV_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          
          # Set default keychain
          security list-keychains -d user -s build.keychain
          security default-keychain -s build.keychain

      - name: Install Provisioning Profile
        if: ${{ env.APPLE_DEV_PROVISIONING_PROFILE_BASE64 != '' }}
        env:
          APPLE_DEV_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_DEV_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$APPLE_DEV_PROVISIONING_PROFILE_BASE64" | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/development.mobileprovision

      # Build with development signing
      - name: Build signed iOS app
        env:
          APPLE_DEV_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEV_CERTIFICATE_BASE64 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd iosApp
          
          # Build for iOS Simulator first
          echo "Building for iOS Simulator..."
          xcodebuild -scheme iosApp \
            -configuration Debug \
            -destination 'id=98CB1710-8715-4EFC-87BF-070976F6498F' \
            CODE_SIGNING_ALLOWED='NO'
          
          # Build for iOS Device
          if [ -n "$APPLE_DEV_CERTIFICATE_BASE64" ]; then
            echo "Building with development signing for device..."
            xcodebuild -scheme iosApp \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              -archivePath KMP_App.xcarchive \
              CODE_SIGN_STYLE=Manual \
              DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
              CODE_SIGN_IDENTITY="iPhone Developer" \
              PROVISIONING_PROFILE_SPECIFIER="development" \
              archive
          else
            echo "Building unsigned for device..."
            xcodebuild -scheme iosApp \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED='NO' \
              ARCHS='arm64'
          fi

      # Create IPA and copy simulator app
      - name: Create IPA and copy simulator app
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd iosApp
          
          # Copy simulator app first
          SIM_APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "KMP*.app" -path "*/Debug-iphonesimulator/*" -type d | head -1)
          if [ -n "$SIM_APP_PATH" ]; then
            echo "Found simulator app at: $SIM_APP_PATH"
            cp -r "$SIM_APP_PATH" ../KMP_App_Simulator.app
            echo "✅ Simulator app copied - can run on iOS Simulator"
          fi
          
          # Create device IPA
          if [ -d "KMP_App.xcarchive" ]; then
            # Create export options
            cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF
          
            # Export archive to IPA
            xcodebuild -exportArchive \
              -archivePath KMP_App.xcarchive \
              -exportPath ./export \
              -exportOptionsPlist exportOptions.plist
          
            # Copy IPA to root
            cp export/*.ipa ../KMP_App_Development.ipa
            echo "✅ Signed device IPA created - can be installed on registered devices"
          else
            # Fallback: create unsigned IPA from device .app
            DEVICE_APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "KMP*.app" -path "*/Debug-iphoneos/*" -type d | head -1)
            if [ -n "$DEVICE_APP_PATH" ]; then
              mkdir -p Payload
              cp -r "$DEVICE_APP_PATH" Payload/
              cd ..
              zip -r KMP_App_Unsigned.ipa iosApp/Payload/
              rm -rf iosApp/Payload
              echo "⚠️ Unsigned device IPA created - won't run on non-jailbroken devices"
            fi
          fi

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-development
          path: |
            KMP_App_Development.ipa
            KMP_App_Unsigned.ipa
          retention-days: 7

      - name: Display build info
        run: |
          echo "Build completed!"
          if [ -f "KMP_App_Development.ipa" ]; then
            echo "✅ Signed development IPA created - can be installed on registered devices"
          elif [ -f "KMP_App_Unsigned.ipa" ]; then
            echo "⚠️ Unsigned IPA created - won't run on non-jailbroken devices"
          fi
          ls -la *.ipa 2>/dev/null || echo "No IPA files found"